/**
 * @lazyorch/adapters — session runner (KD-40), shell adapter, budget hours,
 * adapter registry + discovery (PR-08), first-class coding adapters (PR-09).
 */
export const PACKAGE_NAME = "@lazyorch/adapters" as const;

export type {
  AdapterId,
  SessionKind,
  SessionStatus,
  EffortLevel,
  ApprovalPolicy,
  Usage,
  DoctorResult,
  ContextBundle,
  SessionTaskBlob,
  ReviewDecision,
  QaDecision,
  WorkerMarker,
  StructuredDecision,
  SessionResult,
  RunningAgent,
  AgentSession,
  AgentAdapter,
  SessionRecord,
  SessionsFile,
  SessionMeta,
} from "./types.js";

export {
  scrubEnv,
  scrubText,
  scrubCodingSpawnEnv,
  isSecretEnvKey,
  isCodingVendorEnvKey,
  CODING_VENDOR_ENV_ALLOWLIST,
} from "./scrub.js";
export { killProcessTree, type KillTreeOptions } from "./process-tree.js";

export {
  createSessionRunner,
  generateRunHandle,
  projectRunDir,
  SessionRunnerError,
  materializeSession,
  buildPromptMarkdown,
  substituteStartTemplate,
  emptySkillLoader,
  mapSessionResultToTaskEffect,
  mapCancelEffect,
  decisionSummary,
  parseStructuredDecision,
  parseLastStdoutJsonLine,
  resolveStructuredDecision,
  readResultJsonFile,
  resultJsonPath,
  BudgetHoursTracker,
  sessionsFilePath,
  runSessionsDir,
  sessionDirFor,
  emptySessionsFile,
  readSessionsFile,
  writeSessionsFile,
  registerSession,
  updateSessionRecord,
  clearSession,
  countRunningSessions,
  type SessionRunner,
  type SessionRunnerOptions,
  type StartSessionParams,
  type ManagedRunningAgent,
  type SkillLoader,
  type MaterializeOptions,
  type MaterializeResult,
  type TaskFsmEffect,
  type MappedTaskStatus,
  type MapResultOptions,
  type CancelReason,
  type BudgetHoursLimits,
  type BudgetHoursSnapshot,
  type BudgetHardStopResult,
  type BudgetStopReason,
  type BudgetHoursTrackerOptions,
  type SessionHoursEntry,
} from "./runner/index.js";

export {
  ShellAdapter,
  ShellAdapterError,
  createShellAdapter,
  defaultSpawnImpl,
  checkShellAllowlist,
  commandNameFromArgv,
  DEFAULT_SHELL_ALLOWLIST,
  type ShellAdapterOptions,
  type SpawnImpl,
  type SpawnRequest,
  type SpawnedProcess,
  type ShellAllowlistConfig,
  type AllowlistResult,
} from "./shell/index.js";

export {
  AdapterRegistry,
  createAdapterRegistry,
  BUILTIN_ADAPTER_IDS,
  BUILTIN_CATALOG,
  DEFAULT_TIER_MAPS,
  codingCapabilities,
  shellCapabilities,
  getBuiltinCatalogEntry,
  isBuiltinAdapterId,
  matrixFlagsFor,
  resolveBinary,
  discoverBinary,
  probeAdapter,
  parseVersionString,
  versionMeetsFloor,
  defaultExecImpl,
  resolveAdapterRegistrations,
  buildHealthMatrix,
  doctorAdapters,
  healthRowFrom,
  GenericCliAdapter,
  GenericAdapterError,
  createGenericAdapter,
  splitTemplateArgv,
  templateToArgv,
  type AdapterCapabilities,
  type AdapterRegistration,
  type AdapterHealthRow,
  type AdapterHealthStatus,
  type BuiltinCatalogEntry,
  type BuiltinAdapterId,
  type CapabilityMatrixFlags,
  type HealthMatrix,
  type UsageReporting,
  type DiscoverEnv,
  type DiscoverOptions,
  type DiscoverResult,
  type ExecImpl,
  type ExecResult,
  type ProbeOptions,
  type ResolveRegistryOptions,
  type HealthOptions,
  type AdapterRegistryOptions,
  type TemplateVars,
} from "./registry/index.js";

export {
  resolveSpawnTarget,
  isWindowsShellScript,
  quoteWindowsArg,
  type ResolvedSpawnTarget,
} from "./spawn-policy.js";

export {
  CodingCliAdapter,
  CodingAdapterError,
  createCodingAdapter,
  createCodingAdapterForId,
  buildCodingArgv,
  expandFlagTemplate,
  resolveCodingBinary,
  isUsableModelId,
  CodingArgvError,
  parseUsageFromText,
  parseUsageFromLog,
  usageFromJsonObject,
  CODING_PROFILES,
  FIRST_CLASS_CODING_IDS,
  getCodingProfile,
  isFirstClassCodingId,
  isEffortLevel,
  StartRecorder,
  defaultFakeResult,
  resolveRunMode,
  modeAllowsUnbound,
  type CodingAdapterOptions,
  type BuildCodingArgvOptions,
  type CodingAdapterProfile,
  type FirstClassCodingId,
  type CodingRunMode,
  type RecordedStart,
  type FakeSessionResultFactory,
} from "./coding/index.js";

export {
  createClaudeAdapter,
  claudeRegistration,
  CLAUDE_PROFILE,
} from "./claude/index.js";
export {
  createCodexAdapter,
  codexRegistration,
  CODEX_PROFILE,
} from "./codex/index.js";
export {
  createAgyAdapter,
  agyRegistration,
  AGY_PROFILE,
} from "./agy/index.js";
export {
  createGrokAdapter,
  grokRegistration,
  GROK_PROFILE,
} from "./grok/index.js";
